language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "0.11"
  - "0.10"
before_install:
  - npm install -g grunt-cli
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
